export const actionsConstants = {
    ADD_EXPENCE: "ADD_EXPENCE",
    REMOVE_EXPENCE: "REMOVE_EXPENCE",
    SET_EXPENCES: "SET_EXPENCES",
    FETCH_EXPENCES: "FETCH_EXPENCES",
    EDIT_EXPENCES: "EDIT_EXPENCES"
}